CREATE TABLE tb_event (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    IDENTIFIER VARCHAR(255) NOT NULL,
    LOCAL VARCHAR(255) NOT NULL,
    HOST VARCHAR(255) NOT NULL,
    CAPACITY INTEGER NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    STARTS_AT TIMESTAMP NOT NULL,
    ENDS_AT TIMESTAMP NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);